language: php
php:
  - 5.3
  - 5.4

env:
  - DB=mysql

before_script:
  - cp yourls-tests-config-travis.php yourls-tests-config.php
  - mysql -e 'create database IF NOT EXISTS yourls_tests;'
  - git clone git://github.com/YOURLS/YOURLS.git

script: phpunit --coverage-text

after_script: rm yourls-tests-config.php
