sudo: false
dist: trusty
language: php

env:
  global:
  - DB=mysql

matrix:
  include:
  - php: 5.3
    dist: precise
  - php: 5.4
  - php: 5.5
  - php: 5.6
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: nightly
  - php: hhvm
  fast_finish: true
  allow_failures:
  - php: nightly
  - php: 7.2
  - php: hhvm

before_script:
  - which phpunit
  - phpunit --version
  - mysql --version
  - git clone git://github.com/YOURLS/YOURLS.git
  - |
    export CURRENT_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
    echo "Current Tests branch: $CURRENT_BRANCH"
    cd YOURLS
    if [ `git checkout $CURRENT_BRANCH &> /dev/null; echo $?` == 0 ]
    then
      echo "Using branch $CURRENT_BRANCH for YOURLS as well"
    else
      echo "Using branch master for YOURLS"
    fi
    cd ..
  - mysql -e 'create database IF NOT EXISTS yourls_tests;'
  - cp yourls-tests-config-travis.php YOURLS/user/config.php

script: phpunit --configuration ./phpunit-travis.xml.dist

notifications:
  email: false
