language: php

env:
  global:
  - DB=mysql

matrix:
  include:
  - php: 5.3
    dist: precise
  - php: 5.4
  - php: 5.5
  - php: 5.6
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: nightly
  fast_finish: true
  allow_failures:
  - php: nightly
  - php: 7.2

before_script:
  - which phpunit
  - phpunit --version
  - mysql --version
  - git clone git://github.com/ozh/YOURLS-fr_FR.git user/languages/fr
  - cp user/languages/fr/fr_FR.* user/languages
  - mysql -e 'create database IF NOT EXISTS yourls_tests;'
  - cp tests/data/config/yourls-tests-config-travis.php user/config.php

script: phpunit --configuration phpunit-travis.xml.dist

notifications:
  email: false
