sudo: false

language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
  - php: hhvm

env:
  - DB=mysql

before_script:
  - git clone git://github.com/YOURLS/YOURLS.git
  - mysql -e 'create database IF NOT EXISTS yourls_tests;'
  - cp yourls-tests-config-travis.php YOURLS/user/config.php
  - which phpunit  
  - phpunit --version

script: phpunit --configuration ./phpunit-travis.xml.dist

notifications:
  email: false
