language: php
php:
  - 5.3
  - 5.4

env:
  - DB=mysql

before_script:
  - mysql -e "create database IF NOT EXISTS yourls;" -uroot;
  - git clone git://github.com/YOURLS/YOURLS.git
  - git checkout master
  
